package lk.dialog.corporate.Qr.data;
// Generated Sep 3, 2012 11:08:46 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.io.Serializable;
/**
 * Barcode generated by hbm2java
 */

public class Barcode  implements Serializable {


     private String barcodeId;
     private User user;
     private Campaign campaign;
     private Sizes sizes;
     private Date dateCreated;
     private String type;
     private String bcActionId;
     private String imgeType;
     private String errorCorrectionLevel;
     private Date expDate;
     private String title;
     private String codeName;
     private Set<BarcodeData> barcodeDatas = new HashSet<BarcodeData>(0);
     private Set<UrlHitCount> urlHitCounts = new HashSet<UrlHitCount>(0);
     private Set<UrlHitTime> urlHitTimes = new HashSet<UrlHitTime>(0);

    public Barcode() {
    }

	
    public Barcode(String barcodeId, User user, Sizes sizes, Date dateCreated, String type, String bcActionId, String imgeType, String errorCorrectionLevel, Date expDate) {
        this.barcodeId = barcodeId;
        this.user = user;
        this.sizes = sizes;
        this.dateCreated = dateCreated;
        this.type = type;
        this.bcActionId = bcActionId;
        this.imgeType = imgeType;
        this.errorCorrectionLevel = errorCorrectionLevel;
        this.expDate = expDate;
    }
    public Barcode(String barcodeId, User user, Campaign campaign, Sizes sizes, Date dateCreated, String type, String bcActionId, String imgeType, String errorCorrectionLevel, Date expDate, String title, String codeName, Set<BarcodeData> barcodeDatas, Set<UrlHitCount> urlHitCounts, Set<UrlHitTime> urlHitTimes) {
       this.barcodeId = barcodeId;
       this.user = user;
       this.campaign = campaign;
       this.sizes = sizes;
       this.dateCreated = dateCreated;
       this.type = type;
       this.bcActionId = bcActionId;
       this.imgeType = imgeType;
       this.errorCorrectionLevel = errorCorrectionLevel;
       this.expDate = expDate;
       this.title = title;
       this.codeName = codeName;
       this.barcodeDatas = barcodeDatas;
       this.urlHitCounts = urlHitCounts;
       this.urlHitTimes = urlHitTimes;
    }
   
    public String getBarcodeId() {
        return this.barcodeId;
    }
    
    public void setBarcodeId(String barcodeId) {
        this.barcodeId = barcodeId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Campaign getCampaign() {
        return this.campaign;
    }
    
    public void setCampaign(Campaign campaign) {
        this.campaign = campaign;
    }
    public Sizes getSizes() {
        return this.sizes;
    }
    
    public void setSizes(Sizes sizes) {
        this.sizes = sizes;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getBcActionId() {
        return this.bcActionId;
    }
    
    public void setBcActionId(String bcActionId) {
        this.bcActionId = bcActionId;
    }
    public String getImgeType() {
        return this.imgeType;
    }
    
    public void setImgeType(String imgeType) {
        this.imgeType = imgeType;
    }
    public String getErrorCorrectionLevel() {
        return this.errorCorrectionLevel;
    }
    
    public void setErrorCorrectionLevel(String errorCorrectionLevel) {
        this.errorCorrectionLevel = errorCorrectionLevel;
    }
    public Date getExpDate() {
        return this.expDate;
    }
    
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getCodeName() {
        return this.codeName;
    }
    
    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }
    public Set<BarcodeData> getBarcodeDatas() {
        return this.barcodeDatas;
    }
    
    public void setBarcodeDatas(Set<BarcodeData> barcodeDatas) {
        this.barcodeDatas = barcodeDatas;
    }
    public Set<UrlHitCount> getUrlHitCounts() {
        return this.urlHitCounts;
    }
    
    public void setUrlHitCounts(Set<UrlHitCount> urlHitCounts) {
        this.urlHitCounts = urlHitCounts;
    }

    public Set<UrlHitTime> getUrlHitTimes() {
        return urlHitTimes;
    }

    public void setUrlHitTimes(Set<UrlHitTime> urlHitTimes) {
        this.urlHitTimes = urlHitTimes;
    }




}


