package lk.dialog.corporate.Qr.data;
// Generated Sep 3, 2012 11:08:46 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import org.springframework.stereotype.Component;




/**
 * BarcodeCategoryJasper generated by hbm2java
 */
@Component
public class BarcodeCategoryJasper  implements Serializable {


     private String category;
     private int quentity;

    public BarcodeCategoryJasper() {
    }

    public BarcodeCategoryJasper(String category, int quentity) {
       this.category = category;
       this.quentity = quentity;
    }
   
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public int getQuentity() {
        return this.quentity;
    }
    
    public void setQuentity(int quentity) {
        this.quentity = quentity;
    }




}


