package lk.dialog.corporate.Qr.data;
// Generated Sep 3, 2012 11:08:46 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Campaign generated by hbm2java
 */
@Component
public class Campaign  implements Serializable {


     private Integer campaignId;
     private LobGroup lobGroup;
     private String campaignName;
     private Date startDate;
     private Date expireDate;
     private int campaignStatus;
     private Long createdUserId;
     private Date dateCreated;
     private Set<Barcode> barcodes = new HashSet<Barcode>(0);
     private Set<UserCampaign> userCampaigns = new HashSet<UserCampaign>(0);

    public Campaign() {
    }

	
    public Campaign(LobGroup lobGroup, String campaignName, Date startDate, Date expireDate, int campaignStatus) {
        this.lobGroup = lobGroup;
        this.campaignName = campaignName;
        this.startDate = startDate;
        this.expireDate = expireDate;
        this.campaignStatus = campaignStatus;
    }
    public Campaign(LobGroup lobGroup, String campaignName, Date startDate, Date expireDate, int campaignStatus, Long createdUserId, Date dateCreated, Set<Barcode> barcodes, Set<UserCampaign> userCampaigns) {
       this.lobGroup = lobGroup;
       this.campaignName = campaignName;
       this.startDate = startDate;
       this.expireDate = expireDate;
       this.campaignStatus = campaignStatus;
       this.createdUserId = createdUserId;
       this.dateCreated = dateCreated;
       this.barcodes = barcodes;
       this.userCampaigns = userCampaigns;
    }
   
    public Integer getCampaignId() {
        return this.campaignId;
    }
    
    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }
    public LobGroup getLobGroup() {
        return this.lobGroup;
    }
    
    public void setLobGroup(LobGroup lobGroup) {
        this.lobGroup = lobGroup;
    }
    public String getCampaignName() {
        return this.campaignName;
    }
    
    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
    public int getCampaignStatus() {
        return this.campaignStatus;
    }
    
    public void setCampaignStatus(int campaignStatus) {
        this.campaignStatus = campaignStatus;
    }
    public Long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Set<Barcode> getBarcodes() {
        return this.barcodes;
    }
    
    public void setBarcodes(Set<Barcode> barcodes) {
        this.barcodes = barcodes;
    }
    public Set<UserCampaign> getUserCampaigns() {
        return this.userCampaigns;
    }
    
    public void setUserCampaigns(Set<UserCampaign> userCampaigns) {
        this.userCampaigns = userCampaigns;
    }




}


