package lk.dialog.corporate.Qr.data;
// Generated Sep 3, 2012 11:08:46 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Privileges generated by hbm2java
 */
@Component
public class Privileges  implements Serializable {


     private Integer privilegeId;
     private String privilegeName;
     private String key;
     private Set<UserPrivileges> userPrivilegeses = new HashSet<UserPrivileges>(0);
     private Set<RolePrivilege> rolePrivileges = new HashSet<RolePrivilege>(0);

    public Privileges() {
    }

	
    public Privileges(String privilegeName, String key) {
        this.privilegeName = privilegeName;
        this.key = key;
    }
    public Privileges(String privilegeName, String key, Set<UserPrivileges> userPrivilegeses, Set<RolePrivilege> rolePrivileges) {
       this.privilegeName = privilegeName;
       this.key = key;
       this.userPrivilegeses = userPrivilegeses;
       this.rolePrivileges = rolePrivileges;
    }
   
    public Integer getPrivilegeId() {
        return this.privilegeId;
    }
    
    public void setPrivilegeId(Integer privilegeId) {
        this.privilegeId = privilegeId;
    }
    public String getPrivilegeName() {
        return this.privilegeName;
    }
    
    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName;
    }
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public Set<UserPrivileges> getUserPrivilegeses() {
        return this.userPrivilegeses;
    }
    
    public void setUserPrivilegeses(Set<UserPrivileges> userPrivilegeses) {
        this.userPrivilegeses = userPrivilegeses;
    }
    public Set<RolePrivilege> getRolePrivileges() {
        return this.rolePrivileges;
    }
    
    public void setRolePrivileges(Set<RolePrivilege> rolePrivileges) {
        this.rolePrivileges = rolePrivileges;
    }




}


