package lk.dialog.corporate.Qr.data;
// Generated Sep 3, 2012 11:08:46 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * Role generated by hbm2java
 */
@Component
public class Role  implements Serializable {


     private String roleId;
     private String roleType;
     private Set<User> users = new HashSet<User>(0);
     private Set<RolePrivilege> rolePrivileges = new HashSet<RolePrivilege>(0);

    public Role() {
    }

	
    public Role(String roleId, String roleType) {
        this.roleId = roleId;
        this.roleType = roleType;
    }
    public Role(String roleId, String roleType, Set<User> users, Set<RolePrivilege> rolePrivileges) {
       this.roleId = roleId;
       this.roleType = roleType;
       this.users = users;
       this.rolePrivileges = rolePrivileges;
    }
   
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public String getRoleType() {
        return this.roleType;
    }
    
    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<RolePrivilege> getRolePrivileges() {
        return this.rolePrivileges;
    }
    
    public void setRolePrivileges(Set<RolePrivilege> rolePrivileges) {
        this.rolePrivileges = rolePrivileges;
    }




}


