package lk.dialog.corporate.Qr.data;
// Generated Nov 1, 2012 1:27:08 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * UrlHitTime generated by hbm2java
 */
@Component
public class UrlHitTime  implements Serializable {


     private Long id;
     private Barcode barcode;
     private String realUrl;
     private Date hitTime;

    public UrlHitTime() {
    }

    public UrlHitTime(Barcode barcode, String realUrl, Date hitTime) {
       this.barcode = barcode;
       this.realUrl = realUrl;
       this.hitTime = hitTime;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public Barcode getBarcode() {
        return barcode;
    }

    public void setBarcode(Barcode barcode) {
        this.barcode = barcode;
    }
    
    public String getRealUrl() {
        return this.realUrl;
    }
    
    public void setRealUrl(String realUrl) {
        this.realUrl = realUrl;
    }
    public Date getHitTime() {
        return this.hitTime;
    }
    
    public void setHitTime(Date hitTime) {
        this.hitTime = hitTime;
    }




}


