package lk.dialog.corporate.Qr.data;
// Generated Sep 3, 2012 11:08:46 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import org.springframework.stereotype.Component;

/**
 * UrlHitCount generated by hbm2java
 */
@Component
public class UrlHitCount implements Serializable {

    private Long countId;
    private Barcode barcode;
    private String realUrl;
    private long hitCount;

    public UrlHitCount() {
    }

    public UrlHitCount(Barcode barcode, String realUrl, long hitCount) {
        this.barcode = barcode;
        this.realUrl = realUrl;
        this.hitCount = hitCount;
    }

    public Long getCountId() {
        return this.countId;
    }

    public void setCountId(Long countId) {
        this.countId = countId;
    }

    public Barcode getBarcode() {
        return this.barcode;
    }

    public void setBarcode(Barcode barcode) {
        this.barcode = barcode;
    }

    public String getRealUrl() {
        return this.realUrl;
    }

    public void setRealUrl(String realUrl) {
        this.realUrl = realUrl;
    }

    public long getHitCount() {
        return this.hitCount;
    }

    public void setHitCount(long hitCount) {
        this.hitCount = hitCount;
    }
}
