package lk.dialog.corporate.Qr.data;
// Generated Nov 1, 2012 1:27:08 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * UserAction generated by hbm2java
 */
@Component
public class UserAction  implements Serializable {


     private int actionId;
     private String actionName;
     private String entityType;

    public UserAction() {
    }

	
    public UserAction(int actionId) {
        this.actionId = actionId;
    }
    public UserAction(int actionId, String actionName, String entityType) {
       this.actionId = actionId;
       this.actionName = actionName;
       this.entityType = entityType;
    }
   
    public int getActionId() {
        return this.actionId;
    }
    
    public void setActionId(int actionId) {
        this.actionId = actionId;
    }
    public String getActionName() {
        return this.actionName;
    }
    
    public void setActionName(String actionName) {
        this.actionName = actionName;
    }
    public String getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }




}


