package lk.dialog.corporate.Qr.data;
// Generated Sep 3, 2012 11:08:46 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * UserLogs generated by hbm2java
 */
@Component
public class UserLogs  implements Serializable {


     private int logId;
     private User user;
     private int actionId;
     private String entityId;
     private Date actionDate;
     private String comment;

    public UserLogs() {
    }

	
    public UserLogs(int logId, User user, int actionId, String entityId, Date actionDate) {
        this.logId = logId;
        this.user = user;
        this.actionId = actionId;
        this.entityId = entityId;
        this.actionDate = actionDate;
    }
    public UserLogs(int logId, User user, int actionId, String entityId, Date actionDate, String comment) {
       this.logId = logId;
       this.user = user;
       this.actionId = actionId;
       this.entityId = entityId;
       this.actionDate = actionDate;
       this.comment = comment;
    }
   
    public int getLogId() {
        return this.logId;
    }
    
    public void setLogId(int logId) {
        this.logId = logId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getActionId() {
        return this.actionId;
    }
    
    public void setActionId(int actionId) {
        this.actionId = actionId;
    }
    public String getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }
    public Date getActionDate() {
        return this.actionDate;
    }
    
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


