package lk.dialog.corporate.Qr.data;
// Generated Sep 3, 2012 11:08:46 AM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * User generated by hbm2java
 */
@Component
public class User  implements Serializable {


     private Long userId;
     private Role role;
     private LobGroup lobGroup;
     private Corporate corporate;
     private String userName;
     private String password;
     private String name;
     private String mobile;
     private String email;
     private String description;
     private Date lastLoginDate;
     private Integer userStatus;
     private String designation;
     private Long createdUserId;
     private Date dateCreated;
     private Set<UserLogs> userLogses = new HashSet<UserLogs>(0);
     private Set<UserSize> userSizes = new HashSet<UserSize>(0);
     private Set<Barcode> barcodes = new HashSet<Barcode>(0);
     private Set<UserPrivileges> userPrivilegeses = new HashSet<UserPrivileges>(0);
     private Set<UserCampaign> userCampaigns = new HashSet<UserCampaign>(0);

    public User() {
    }

	
    public User(Role role, Corporate corporate, String userName, String password, String name, String mobile, String email) {
        this.role = role;
        this.corporate = corporate;
        this.userName = userName;
        this.password = password;
        this.name = name;
        this.mobile = mobile;
        this.email = email;
    }
    public User(Role role, LobGroup lobGroup, Corporate corporate, String userName, String password, String name, String mobile, String email, String description, Date lastLoginDate, Integer userStatus, String designation, Long createdUserId, Date dateCreated, Set<UserLogs> userLogses, Set<UserSize> userSizes, Set<Barcode> barcodes, Set<UserPrivileges> userPrivilegeses, Set<UserCampaign> userCampaigns) {
       this.role = role;
       this.lobGroup = lobGroup;
       this.corporate = corporate;
       this.userName = userName;
       this.password = password;
       this.name = name;
       this.mobile = mobile;
       this.email = email;
       this.description = description;
       this.lastLoginDate = lastLoginDate;
       this.userStatus = userStatus;
       this.designation = designation;
       this.createdUserId = createdUserId;
       this.dateCreated = dateCreated;
       this.userLogses = userLogses;
       this.userSizes = userSizes;
       this.barcodes = barcodes;
       this.userPrivilegeses = userPrivilegeses;
       this.userCampaigns = userCampaigns;
    }
   
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public LobGroup getLobGroup() {
        return this.lobGroup;
    }
    
    public void setLobGroup(LobGroup lobGroup) {
        this.lobGroup = lobGroup;
    }
    public Corporate getCorporate() {
        return this.corporate;
    }
    
    public void setCorporate(Corporate corporate) {
        this.corporate = corporate;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getLastLoginDate() {
        return this.lastLoginDate;
    }
    
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }
    public Integer getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public Long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Set<UserLogs> getUserLogses() {
        return this.userLogses;
    }
    
    public void setUserLogses(Set<UserLogs> userLogses) {
        this.userLogses = userLogses;
    }
    public Set<UserSize> getUserSizes() {
        return this.userSizes;
    }
    
    public void setUserSizes(Set<UserSize> userSizes) {
        this.userSizes = userSizes;
    }
    public Set<Barcode> getBarcodes() {
        return this.barcodes;
    }
    
    public void setBarcodes(Set<Barcode> barcodes) {
        this.barcodes = barcodes;
    }
    public Set<UserPrivileges> getUserPrivilegeses() {
        return this.userPrivilegeses;
    }
    
    public void setUserPrivilegeses(Set<UserPrivileges> userPrivilegeses) {
        this.userPrivilegeses = userPrivilegeses;
    }
    public Set<UserCampaign> getUserCampaigns() {
        return this.userCampaigns;
    }
    
    public void setUserCampaigns(Set<UserCampaign> userCampaigns) {
        this.userCampaigns = userCampaigns;
    }




}


