package lk.dialog.corporate.Qr.data;
// Generated Sep 3, 2012 11:08:46 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import org.springframework.stereotype.Component;




/**
 * UserCampaign generated by hbm2java
 */
@Component
public class UserCampaign  implements Serializable {


     private Integer userCampaignId;
     private User user;
     private Campaign campaign;
     private int owner;

    public UserCampaign() {
    }

    public UserCampaign(User user, Campaign campaign, int owner) {
       this.user = user;
       this.campaign = campaign;
       this.owner = owner;
    }
   
    public Integer getUserCampaignId() {
        return this.userCampaignId;
    }
    
    public void setUserCampaignId(Integer userCampaignId) {
        this.userCampaignId = userCampaignId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Campaign getCampaign() {
        return this.campaign;
    }
    
    public void setCampaign(Campaign campaign) {
        this.campaign = campaign;
    }
    public int getOwner() {
        return this.owner;
    }
    
    public void setOwner(int owner) {
        this.owner = owner;
    }




}


