package lk.dialog.corporate.Qr.data;
// Generated Sep 3, 2012 11:08:46 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import org.springframework.stereotype.Component;




/**
 * UserSize generated by hbm2java
 */
@Component
public class UserSize  implements Serializable {


     private String id;
     private User user;
     private Sizes sizes;

    public UserSize() {
    }

    public UserSize(String id, User user, Sizes sizes) {
       this.id = id;
       this.user = user;
       this.sizes = sizes;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Sizes getSizes() {
        return this.sizes;
    }
    
    public void setSizes(Sizes sizes) {
        this.sizes = sizes;
    }




}


