package lk.dialog.corporate.Qr.data;
// Generated Sep 3, 2012 11:08:46 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import org.springframework.stereotype.Component;




/**
 * UserPrivileges generated by hbm2java
 */
@Component
public class UserPrivileges  implements Serializable {


     private Integer userPrivilegeId;
     private User user;
     private Privileges privileges;

    public UserPrivileges() {
    }

    public UserPrivileges(User user, Privileges privileges) {
       this.user = user;
       this.privileges = privileges;
    }
   
    public Integer getUserPrivilegeId() {
        return this.userPrivilegeId;
    }
    
    public void setUserPrivilegeId(Integer userPrivilegeId) {
        this.userPrivilegeId = userPrivilegeId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Privileges getPrivileges() {
        return this.privileges;
    }
    
    public void setPrivileges(Privileges privileges) {
        this.privileges = privileges;
    }




}


